baseurl      = "localhost"
title        = "Ray's Personal Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  date    = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Welcome to my personal corner of the Internet"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Ray's Personal Blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "A simple theme for Hugo"

    [languages.en.params.logo]
      logoText = "Ray's Personal Blog"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "gallery"
    name       = "Gallery"
    url        = "/gallery"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/raymonshields"

[[params.socialIcons]]
name = "email"
url = "raymonshields1@gmail.com"

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"

[[module.imports]]
path = "github.com/mfg92/hugo-shortcode-gallery"